<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUjlth6b\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUjlth6b/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUjlth6b.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUjlth6b\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUjlth6b\appProdProjectContainer([
    'container.build_hash' => 'Ujlth6b',
    'container.build_id' => '1b939d1c',
    'container.build_time' => 1605095287,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUjlth6b');
