<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIvrxktc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIvrxktc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIvrxktc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIvrxktc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIvrxktc\appDevDebugProjectContainer([
    'container.build_hash' => 'Ivrxktc',
    'container.build_id' => '875da598',
    'container.build_time' => 1609962290,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIvrxktc');
